#!/usr/bin/env bash
# install-miner.sh — install (or refresh) the vault miner user unit and its launcher wrappers.
#
# Run once per machine. Idempotent: re-running after a plugin upgrade only rewrites the wrappers.
#   bash systemd/install-miner.sh          install + enable + start
#   bash systemd/install-miner.sh --status what is installed right now

set -euo pipefail

self_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
bin="$HOME/.local/bin"
units="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"

# The wrapper resolves the NEWEST installed plugin version at exec time, and falls back to this
# checkout when the plugin is not installed from a marketplace (a dev box running from the repo).
write_wrapper() {   # name, script
  mkdir -p "$bin"
  cat > "$bin/$1" <<WRAP
#!/usr/bin/env bash
# generated by claude-vault install-miner.sh — resolves the newest installed plugin version
newest=\$(ls -d "\$HOME"/.claude/plugins/cache/*/vault/*/ 2>/dev/null | sort -V | tail -1)
if [[ -n "\$newest" && -f "\${newest}skills/vault/scripts/$2" ]]; then
  exec bash "\${newest}skills/vault/scripts/$2" "\$@"
fi
exec bash "$(cd "$self_dir/.." && pwd)/skills/vault/scripts/$2" "\$@"
WRAP
  chmod +x "$bin/$1"
}

if [[ "${1:-}" == "--status" ]]; then
  echo "wrapper:  $(ls -l "$bin/vault-miner" 2>/dev/null || echo 'not installed')"
  echo "unit:     $(systemctl --user is-enabled vault-miner 2>/dev/null || echo 'not installed') / $(systemctl --user is-active vault-miner 2>/dev/null || echo inactive)"
  echo "linger:   $(loginctl show-user "$USER" -p Linger --value 2>/dev/null || echo '?')"
  exit 0
fi

write_wrapper vault-miner miner.sh
write_wrapper vault-watch watch.sh
mkdir -p "$units"
install -m 0644 "$self_dir/vault-miner.service" "$units/vault-miner.service"
systemctl --user daemon-reload
systemctl --user enable --now vault-miner

# Without linger the unit dies at logout and does not come back until the next login — a miner that
# stops with the desktop session is the silent gap this whole design exists to close.
if [[ "$(loginctl show-user "$USER" -p Linger --value 2>/dev/null)" != "yes" ]]; then
  echo "⚠ linger is OFF — the miner will not run outside a login session."
  echo "  enable it with:  sudo loginctl enable-linger $USER"
fi

echo "✓ vault-miner installed: $(systemctl --user is-active vault-miner)"
echo "  watch it:  vault-watch        (optional, read-only)"
echo "  logs:      journalctl --user -u vault-miner -f"
